// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module MIRROR_CARRYOUT_ONLY (
Out,Vdd,GND,X_i,Th_i,Cin );
output  Out;
input  Vdd;
input  GND;
input  X_i;
input  Th_i;
input  Cin;
wire Cin;
wire Vdd;
wire X_i;
wire net8;
wire net21;
wire GND;
wire net10;
wire Out;
wire net20;
wire Th_i;

nmos1v    
 NM4  ( .S( net20 ), .G( X_i ), .B( GND ), .D( Out ) );

nmos1v    
 NM3  ( .S( GND ), .G( Th_i ), .B( GND ), .D( net20 ) );

nmos1v    
 NM2  ( .S( GND ), .G( Th_i ), .B( GND ), .D( net8 ) );

nmos1v    
 NM1  ( .S( GND ), .G( X_i ), .B( GND ), .D( net8 ) );

nmos1v    
 NM0  ( .S( net8 ), .G( Cin ), .B( GND ), .D( Out ) );

pmos1v    
 PM4  ( .S( Vdd ), .G( Th_i ), .B( Vdd ), .D( net21 ) );

pmos1v    
 PM3  ( .S( net21 ), .G( X_i ), .B( Vdd ), .D( Out ) );

pmos1v    
 PM2  ( .S( net10 ), .G( Cin ), .B( Vdd ), .D( Out ) );

pmos1v    
 PM1  ( .S( Vdd ), .G( Th_i ), .B( Vdd ), .D( net10 ) );

pmos1v    
 PM0  ( .S( Vdd ), .G( X_i ), .B( Vdd ), .D( net10 ) );

endmodule

