// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module MUX (
In0,In1,GND,Out,Vdd,SelBar );
input  In0;
input  In1;
input  GND;
output  Out;
input  Vdd;
input  SelBar;
wire Vdd;
wire net07;
wire In1;
wire In0;
wire GND;
wire SelBar;
wire Out;

pmos1v    
 PM1  ( .S( In1 ), .G( SelBar ), .B( Vdd ), .D( Out ) );

pmos1v    
 PM0  ( .S( In0 ), .G( net07 ), .B( Vdd ), .D( Out ) );

INV_S    
 I19  ( .Vdd( Vdd ), .In( SelBar ), .GND( GND ), .Out( net07 ) );

nmos1v    
 NM1  ( .S( Out ), .G( net07 ), .B( GND ), .D( In1 ) );

nmos1v    
 NM0  ( .S( Out ), .G( SelBar ), .B( GND ), .D( In0 ) );

endmodule

